baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Dirk Courteaux Guitars"
theme = "guitars"
author = "Martijn Courteaux"

[params]
  author = "Martijn Courteaux"
  year = "2015"
  welcome = "This is a test"