baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Dirk Courteaux Guitars"
theme = "guitars"
author = "Martijn Courteaux"

[params]
  author = "Martijn Courteaux"
  year = "2015"
  welcome = "My name is **Dirk**. I'm a passionate guitar builder. I'm a student at **CMB Puurs** where I completed the for years training of classical guitar building. This schoolyear (2015-2016) I will finish the steelstring training. On this website, I will showcase my work. There are three divisions being Clssical giutars, Steelstring guitars and Electical guitars"
  subtitle = "Handcrafted high-quality guitars"
  email = "dirk.courteaux@gmail.com"